Repository Jan-IngenHousz-Institute/open-jii, pull requests merged in 2025-05, with the labels that each got.

#189 feat(web): adds ts-rest and react-query v5 integration
  apps/mobile/src/screens/bluetooth-devices-list-screen/bluetooth-devices-list-screen.tsx
  apps/web/app/layout.tsx
  apps/web/hooks/experiment/useExperiment/useExperiment.ts
  apps/web/hooks/experiment/useExperimentCreate/useExperimentCreate.ts
  apps/web/hooks/experiment/useExperimentDelete/useExperimentDelete.ts
  apps/web/hooks/experiment/useExperimentMemberAdd/useExperimentMemberAdd.ts
  apps/web/hooks/experiment/useExperimentMemberRemove/useExperimentMemberRemove.ts
  apps/web/hooks/experiment/useExperimentMembers/useExperimentMembers.ts
  apps/web/hooks/experiment/useExperimentUpdate/useExperimentUpdate.ts
  apps/web/hooks/experiment/useExperiments/useExperiments.ts
  apps/web/lib/tsr.ts
  apps/web/package.json
  apps/web/providers/QueryProvider.tsx
  packages/ui/src/button.tsx
  packages/ui/src/dropdown-menu.tsx
  packages/ui/src/form.tsx
  packages/ui/src/input.tsx
  packages/ui/src/label.tsx
  packages/ui/src/toast.tsx
  pnpm-lock.yaml
  tooling/tailwind/eslint.config.js
Labels: enhancement

#206 feat: CICD Tofu & Art. fixes
  .github/actions/blt/action.yml
  .github/actions/tofu/action.yml
  .github/workflows/deployment-template.yml
  .github/workflows/deployment-template_OLD.yml
  .github/workflows/pr.yml
  infrastructure/modules/iam-oidc/main.tf
Labels: enhancement, ci/cd

#253 fix(infra): Initial code for PR workflow fix
  .github/workflows/deployment-template_OLD.yml
  .github/workflows/pr.yml
Labels: bug, enhancement, ci/cd

#255 fix(infra): Fix/pr workflow 251 - amend oidc in tofu action
  .github/actions/tofu/action.yml
Labels: enhancement, ci/cd

#257 fix(infra): iam-oidc arn-256
  infrastructure/modules/iam-oidc/data.tf
  infrastructure/modules/iam-oidc/main.tf
Labels: enhancement

#261 feat(infra): Updating the Cognito Pools perm. for deploy policy
  infrastructure/modules/iam-oidc/main.tf
Labels: enhancement

#259 fix(infra): Fix/pr workflow 251
  .github/actions/tofu/action.yml
  .github/workflows/deployment-template.yml
  .github/workflows/deployment-template_OLD.yml
  .github/workflows/pr.yml
  infrastructure/env/dev/variables.tf
Labels: enhancement, ci/cd

#265 fix(infra): Bugfix/tf typo-264
  infrastructure/env/dev/main.tf
  infrastructure/modules/iam-oidc/main.tf
  infrastructure/modules/iam-oidc/variables.tf
Labels: bug

#266 feat(infra): Add Role & Region in pr.yml when calling tofu action
  .github/workflows/pr.yml
Labels: ci/cd

#269 feat(cdcd): Add temp dispatch to PR workflow
  .github/workflows/pr.yml
Labels: ci/cd

#272 feat(cicd): Feat/cicd backend 270
  .github/actions/bpd/action.yml
  .github/actions/btn/action.yml
  .github/workflows/build-and-push.yml
Labels: enhancement, ci/cd
